// Generated by jextract

package org.sdl3;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _onexit_table_t {
 *     _PVFV *_first;
 *     _PVFV *_last;
 *     _PVFV *_end;
 * }
 * }
 */
public class _onexit_table_t {

    _onexit_table_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL.C_POINTER.withName("_first"),
        SDL.C_POINTER.withName("_last"),
        SDL.C_POINTER.withName("_end")
    ).withName("_onexit_table_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout _first$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("_first"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _PVFV *_first
     * }
     */
    public static final AddressLayout _first$layout() {
        return _first$LAYOUT;
    }

    private static final long _first$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _PVFV *_first
     * }
     */
    public static final long _first$offset() {
        return _first$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _PVFV *_first
     * }
     */
    public static MemorySegment _first(MemorySegment struct) {
        return struct.get(_first$LAYOUT, _first$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _PVFV *_first
     * }
     */
    public static void _first(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(_first$LAYOUT, _first$OFFSET, fieldValue);
    }

    private static final AddressLayout _last$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("_last"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _PVFV *_last
     * }
     */
    public static final AddressLayout _last$layout() {
        return _last$LAYOUT;
    }

    private static final long _last$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _PVFV *_last
     * }
     */
    public static final long _last$offset() {
        return _last$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _PVFV *_last
     * }
     */
    public static MemorySegment _last(MemorySegment struct) {
        return struct.get(_last$LAYOUT, _last$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _PVFV *_last
     * }
     */
    public static void _last(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(_last$LAYOUT, _last$OFFSET, fieldValue);
    }

    private static final AddressLayout _end$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("_end"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _PVFV *_end
     * }
     */
    public static final AddressLayout _end$layout() {
        return _end$LAYOUT;
    }

    private static final long _end$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _PVFV *_end
     * }
     */
    public static final long _end$offset() {
        return _end$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _PVFV *_end
     * }
     */
    public static MemorySegment _end(MemorySegment struct) {
        return struct.get(_end$LAYOUT, _end$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _PVFV *_end
     * }
     */
    public static void _end(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(_end$LAYOUT, _end$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

