// Generated by jextract

package org.sdl3;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class SDL extends SDL_h_1 {

    SDL() {
        // Should not be called directly
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_VITA_PVR_INIT "SDL_VITA_PVR_INIT"
     * }
     */
    public static MemorySegment SDL_HINT_VITA_PVR_INIT() {
        class Holder {
            static final MemorySegment SDL_HINT_VITA_PVR_INIT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_VITA_PVR_INIT");
        }
        return Holder.SDL_HINT_VITA_PVR_INIT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_VITA_RESOLUTION "SDL_VITA_RESOLUTION"
     * }
     */
    public static MemorySegment SDL_HINT_VITA_RESOLUTION() {
        class Holder {
            static final MemorySegment SDL_HINT_VITA_RESOLUTION
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_VITA_RESOLUTION");
        }
        return Holder.SDL_HINT_VITA_RESOLUTION;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_VITA_PVR_OPENGL "SDL_VITA_PVR_OPENGL"
     * }
     */
    public static MemorySegment SDL_HINT_VITA_PVR_OPENGL() {
        class Holder {
            static final MemorySegment SDL_HINT_VITA_PVR_OPENGL
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_VITA_PVR_OPENGL");
        }
        return Holder.SDL_HINT_VITA_PVR_OPENGL;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_VITA_TOUCH_MOUSE_DEVICE "SDL_VITA_TOUCH_MOUSE_DEVICE"
     * }
     */
    public static MemorySegment SDL_HINT_VITA_TOUCH_MOUSE_DEVICE() {
        class Holder {
            static final MemorySegment SDL_HINT_VITA_TOUCH_MOUSE_DEVICE
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_VITA_TOUCH_MOUSE_DEVICE");
        }
        return Holder.SDL_HINT_VITA_TOUCH_MOUSE_DEVICE;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_VULKAN_DISPLAY "SDL_VULKAN_DISPLAY"
     * }
     */
    public static MemorySegment SDL_HINT_VULKAN_DISPLAY() {
        class Holder {
            static final MemorySegment SDL_HINT_VULKAN_DISPLAY
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_VULKAN_DISPLAY");
        }
        return Holder.SDL_HINT_VULKAN_DISPLAY;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_VULKAN_LIBRARY "SDL_VULKAN_LIBRARY"
     * }
     */
    public static MemorySegment SDL_HINT_VULKAN_LIBRARY() {
        class Holder {
            static final MemorySegment SDL_HINT_VULKAN_LIBRARY
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_VULKAN_LIBRARY");
        }
        return Holder.SDL_HINT_VULKAN_LIBRARY;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WAVE_FACT_CHUNK "SDL_WAVE_FACT_CHUNK"
     * }
     */
    public static MemorySegment SDL_HINT_WAVE_FACT_CHUNK() {
        class Holder {
            static final MemorySegment SDL_HINT_WAVE_FACT_CHUNK
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WAVE_FACT_CHUNK");
        }
        return Holder.SDL_HINT_WAVE_FACT_CHUNK;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WAVE_CHUNK_LIMIT "SDL_WAVE_CHUNK_LIMIT"
     * }
     */
    public static MemorySegment SDL_HINT_WAVE_CHUNK_LIMIT() {
        class Holder {
            static final MemorySegment SDL_HINT_WAVE_CHUNK_LIMIT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WAVE_CHUNK_LIMIT");
        }
        return Holder.SDL_HINT_WAVE_CHUNK_LIMIT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WAVE_RIFF_CHUNK_SIZE "SDL_WAVE_RIFF_CHUNK_SIZE"
     * }
     */
    public static MemorySegment SDL_HINT_WAVE_RIFF_CHUNK_SIZE() {
        class Holder {
            static final MemorySegment SDL_HINT_WAVE_RIFF_CHUNK_SIZE
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WAVE_RIFF_CHUNK_SIZE");
        }
        return Holder.SDL_HINT_WAVE_RIFF_CHUNK_SIZE;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WAVE_TRUNCATION "SDL_WAVE_TRUNCATION"
     * }
     */
    public static MemorySegment SDL_HINT_WAVE_TRUNCATION() {
        class Holder {
            static final MemorySegment SDL_HINT_WAVE_TRUNCATION
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WAVE_TRUNCATION");
        }
        return Holder.SDL_HINT_WAVE_TRUNCATION;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOW_ACTIVATE_WHEN_RAISED "SDL_WINDOW_ACTIVATE_WHEN_RAISED"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOW_ACTIVATE_WHEN_RAISED() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOW_ACTIVATE_WHEN_RAISED
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOW_ACTIVATE_WHEN_RAISED");
        }
        return Holder.SDL_HINT_WINDOW_ACTIVATE_WHEN_RAISED;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOW_ACTIVATE_WHEN_SHOWN "SDL_WINDOW_ACTIVATE_WHEN_SHOWN"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOW_ACTIVATE_WHEN_SHOWN() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOW_ACTIVATE_WHEN_SHOWN
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOW_ACTIVATE_WHEN_SHOWN");
        }
        return Holder.SDL_HINT_WINDOW_ACTIVATE_WHEN_SHOWN;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOW_ALLOW_TOPMOST "SDL_WINDOW_ALLOW_TOPMOST"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOW_ALLOW_TOPMOST() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOW_ALLOW_TOPMOST
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOW_ALLOW_TOPMOST");
        }
        return Holder.SDL_HINT_WINDOW_ALLOW_TOPMOST;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN "SDL_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN");
        }
        return Holder.SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOWS_CLOSE_ON_ALT_F4 "SDL_WINDOWS_CLOSE_ON_ALT_F4"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOWS_CLOSE_ON_ALT_F4() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOWS_CLOSE_ON_ALT_F4
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOWS_CLOSE_ON_ALT_F4");
        }
        return Holder.SDL_HINT_WINDOWS_CLOSE_ON_ALT_F4;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOWS_ENABLE_MENU_MNEMONICS "SDL_WINDOWS_ENABLE_MENU_MNEMONICS"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOWS_ENABLE_MENU_MNEMONICS() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOWS_ENABLE_MENU_MNEMONICS
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOWS_ENABLE_MENU_MNEMONICS");
        }
        return Holder.SDL_HINT_WINDOWS_ENABLE_MENU_MNEMONICS;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP "SDL_WINDOWS_ENABLE_MESSAGELOOP"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOWS_ENABLE_MESSAGELOOP");
        }
        return Holder.SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOWS_GAMEINPUT "SDL_WINDOWS_GAMEINPUT"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOWS_GAMEINPUT() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOWS_GAMEINPUT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOWS_GAMEINPUT");
        }
        return Holder.SDL_HINT_WINDOWS_GAMEINPUT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOWS_RAW_KEYBOARD "SDL_WINDOWS_RAW_KEYBOARD"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOWS_RAW_KEYBOARD() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOWS_RAW_KEYBOARD
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOWS_RAW_KEYBOARD");
        }
        return Holder.SDL_HINT_WINDOWS_RAW_KEYBOARD;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOWS_FORCE_SEMAPHORE_KERNEL "SDL_WINDOWS_FORCE_SEMAPHORE_KERNEL"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOWS_FORCE_SEMAPHORE_KERNEL() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOWS_FORCE_SEMAPHORE_KERNEL
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOWS_FORCE_SEMAPHORE_KERNEL");
        }
        return Holder.SDL_HINT_WINDOWS_FORCE_SEMAPHORE_KERNEL;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOWS_INTRESOURCE_ICON "SDL_WINDOWS_INTRESOURCE_ICON"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOWS_INTRESOURCE_ICON() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOWS_INTRESOURCE_ICON
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOWS_INTRESOURCE_ICON");
        }
        return Holder.SDL_HINT_WINDOWS_INTRESOURCE_ICON;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL "SDL_WINDOWS_INTRESOURCE_ICON_SMALL"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOWS_INTRESOURCE_ICON_SMALL");
        }
        return Holder.SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOWS_USE_D3D9EX "SDL_WINDOWS_USE_D3D9EX"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOWS_USE_D3D9EX() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOWS_USE_D3D9EX
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOWS_USE_D3D9EX");
        }
        return Holder.SDL_HINT_WINDOWS_USE_D3D9EX;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_WINDOWS_ERASE_BACKGROUND_MODE "SDL_WINDOWS_ERASE_BACKGROUND_MODE"
     * }
     */
    public static MemorySegment SDL_HINT_WINDOWS_ERASE_BACKGROUND_MODE() {
        class Holder {
            static final MemorySegment SDL_HINT_WINDOWS_ERASE_BACKGROUND_MODE
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_WINDOWS_ERASE_BACKGROUND_MODE");
        }
        return Holder.SDL_HINT_WINDOWS_ERASE_BACKGROUND_MODE;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_X11_FORCE_OVERRIDE_REDIRECT "SDL_X11_FORCE_OVERRIDE_REDIRECT"
     * }
     */
    public static MemorySegment SDL_HINT_X11_FORCE_OVERRIDE_REDIRECT() {
        class Holder {
            static final MemorySegment SDL_HINT_X11_FORCE_OVERRIDE_REDIRECT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_X11_FORCE_OVERRIDE_REDIRECT");
        }
        return Holder.SDL_HINT_X11_FORCE_OVERRIDE_REDIRECT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_X11_WINDOW_TYPE "SDL_X11_WINDOW_TYPE"
     * }
     */
    public static MemorySegment SDL_HINT_X11_WINDOW_TYPE() {
        class Holder {
            static final MemorySegment SDL_HINT_X11_WINDOW_TYPE
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_X11_WINDOW_TYPE");
        }
        return Holder.SDL_HINT_X11_WINDOW_TYPE;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_X11_XCB_LIBRARY "SDL_X11_XCB_LIBRARY"
     * }
     */
    public static MemorySegment SDL_HINT_X11_XCB_LIBRARY() {
        class Holder {
            static final MemorySegment SDL_HINT_X11_XCB_LIBRARY
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_X11_XCB_LIBRARY");
        }
        return Holder.SDL_HINT_X11_XCB_LIBRARY;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_XINPUT_ENABLED "SDL_XINPUT_ENABLED"
     * }
     */
    public static MemorySegment SDL_HINT_XINPUT_ENABLED() {
        class Holder {
            static final MemorySegment SDL_HINT_XINPUT_ENABLED
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_XINPUT_ENABLED");
        }
        return Holder.SDL_HINT_XINPUT_ENABLED;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_ASSERT "SDL_ASSERT"
     * }
     */
    public static MemorySegment SDL_HINT_ASSERT() {
        class Holder {
            static final MemorySegment SDL_HINT_ASSERT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_ASSERT");
        }
        return Holder.SDL_HINT_ASSERT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_PEN_MOUSE_EVENTS "SDL_PEN_MOUSE_EVENTS"
     * }
     */
    public static MemorySegment SDL_HINT_PEN_MOUSE_EVENTS() {
        class Holder {
            static final MemorySegment SDL_HINT_PEN_MOUSE_EVENTS
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_PEN_MOUSE_EVENTS");
        }
        return Holder.SDL_HINT_PEN_MOUSE_EVENTS;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_HINT_PEN_TOUCH_EVENTS "SDL_PEN_TOUCH_EVENTS"
     * }
     */
    public static MemorySegment SDL_HINT_PEN_TOUCH_EVENTS() {
        class Holder {
            static final MemorySegment SDL_HINT_PEN_TOUCH_EVENTS
                = SDL.LIBRARY_ARENA.allocateFrom("SDL_PEN_TOUCH_EVENTS");
        }
        return Holder.SDL_HINT_PEN_TOUCH_EVENTS;
    }
    private static final int SDL_INIT_AUDIO = (int)16L;
    /**
     * {@snippet lang=c :
     * #define SDL_INIT_AUDIO 16
     * }
     */
    public static int SDL_INIT_AUDIO() {
        return SDL_INIT_AUDIO;
    }
    private static final int SDL_INIT_VIDEO = (int)32L;
    /**
     * {@snippet lang=c :
     * #define SDL_INIT_VIDEO 32
     * }
     */
    public static int SDL_INIT_VIDEO() {
        return SDL_INIT_VIDEO;
    }
    private static final int SDL_INIT_JOYSTICK = (int)512L;
    /**
     * {@snippet lang=c :
     * #define SDL_INIT_JOYSTICK 512
     * }
     */
    public static int SDL_INIT_JOYSTICK() {
        return SDL_INIT_JOYSTICK;
    }
    private static final int SDL_INIT_HAPTIC = (int)4096L;
    /**
     * {@snippet lang=c :
     * #define SDL_INIT_HAPTIC 4096
     * }
     */
    public static int SDL_INIT_HAPTIC() {
        return SDL_INIT_HAPTIC;
    }
    private static final int SDL_INIT_GAMEPAD = (int)8192L;
    /**
     * {@snippet lang=c :
     * #define SDL_INIT_GAMEPAD 8192
     * }
     */
    public static int SDL_INIT_GAMEPAD() {
        return SDL_INIT_GAMEPAD;
    }
    private static final int SDL_INIT_EVENTS = (int)16384L;
    /**
     * {@snippet lang=c :
     * #define SDL_INIT_EVENTS 16384
     * }
     */
    public static int SDL_INIT_EVENTS() {
        return SDL_INIT_EVENTS;
    }
    private static final int SDL_INIT_SENSOR = (int)32768L;
    /**
     * {@snippet lang=c :
     * #define SDL_INIT_SENSOR 32768
     * }
     */
    public static int SDL_INIT_SENSOR() {
        return SDL_INIT_SENSOR;
    }
    private static final int SDL_INIT_CAMERA = (int)65536L;
    /**
     * {@snippet lang=c :
     * #define SDL_INIT_CAMERA 65536
     * }
     */
    public static int SDL_INIT_CAMERA() {
        return SDL_INIT_CAMERA;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_APP_METADATA_NAME_STRING "SDL.app.metadata.name"
     * }
     */
    public static MemorySegment SDL_PROP_APP_METADATA_NAME_STRING() {
        class Holder {
            static final MemorySegment SDL_PROP_APP_METADATA_NAME_STRING
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.app.metadata.name");
        }
        return Holder.SDL_PROP_APP_METADATA_NAME_STRING;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_APP_METADATA_VERSION_STRING "SDL.app.metadata.version"
     * }
     */
    public static MemorySegment SDL_PROP_APP_METADATA_VERSION_STRING() {
        class Holder {
            static final MemorySegment SDL_PROP_APP_METADATA_VERSION_STRING
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.app.metadata.version");
        }
        return Holder.SDL_PROP_APP_METADATA_VERSION_STRING;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_APP_METADATA_IDENTIFIER_STRING "SDL.app.metadata.identifier"
     * }
     */
    public static MemorySegment SDL_PROP_APP_METADATA_IDENTIFIER_STRING() {
        class Holder {
            static final MemorySegment SDL_PROP_APP_METADATA_IDENTIFIER_STRING
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.app.metadata.identifier");
        }
        return Holder.SDL_PROP_APP_METADATA_IDENTIFIER_STRING;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_APP_METADATA_CREATOR_STRING "SDL.app.metadata.creator"
     * }
     */
    public static MemorySegment SDL_PROP_APP_METADATA_CREATOR_STRING() {
        class Holder {
            static final MemorySegment SDL_PROP_APP_METADATA_CREATOR_STRING
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.app.metadata.creator");
        }
        return Holder.SDL_PROP_APP_METADATA_CREATOR_STRING;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_APP_METADATA_COPYRIGHT_STRING "SDL.app.metadata.copyright"
     * }
     */
    public static MemorySegment SDL_PROP_APP_METADATA_COPYRIGHT_STRING() {
        class Holder {
            static final MemorySegment SDL_PROP_APP_METADATA_COPYRIGHT_STRING
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.app.metadata.copyright");
        }
        return Holder.SDL_PROP_APP_METADATA_COPYRIGHT_STRING;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_APP_METADATA_URL_STRING "SDL.app.metadata.url"
     * }
     */
    public static MemorySegment SDL_PROP_APP_METADATA_URL_STRING() {
        class Holder {
            static final MemorySegment SDL_PROP_APP_METADATA_URL_STRING
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.app.metadata.url");
        }
        return Holder.SDL_PROP_APP_METADATA_URL_STRING;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_APP_METADATA_TYPE_STRING "SDL.app.metadata.type"
     * }
     */
    public static MemorySegment SDL_PROP_APP_METADATA_TYPE_STRING() {
        class Holder {
            static final MemorySegment SDL_PROP_APP_METADATA_TYPE_STRING
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.app.metadata.type");
        }
        return Holder.SDL_PROP_APP_METADATA_TYPE_STRING;
    }
    private static final int SDL_MESSAGEBOX_ERROR = (int)16L;
    /**
     * {@snippet lang=c :
     * #define SDL_MESSAGEBOX_ERROR 16
     * }
     */
    public static int SDL_MESSAGEBOX_ERROR() {
        return SDL_MESSAGEBOX_ERROR;
    }
    private static final int SDL_MESSAGEBOX_WARNING = (int)32L;
    /**
     * {@snippet lang=c :
     * #define SDL_MESSAGEBOX_WARNING 32
     * }
     */
    public static int SDL_MESSAGEBOX_WARNING() {
        return SDL_MESSAGEBOX_WARNING;
    }
    private static final int SDL_MESSAGEBOX_INFORMATION = (int)64L;
    /**
     * {@snippet lang=c :
     * #define SDL_MESSAGEBOX_INFORMATION 64
     * }
     */
    public static int SDL_MESSAGEBOX_INFORMATION() {
        return SDL_MESSAGEBOX_INFORMATION;
    }
    private static final int SDL_MESSAGEBOX_BUTTONS_LEFT_TO_RIGHT = (int)128L;
    /**
     * {@snippet lang=c :
     * #define SDL_MESSAGEBOX_BUTTONS_LEFT_TO_RIGHT 128
     * }
     */
    public static int SDL_MESSAGEBOX_BUTTONS_LEFT_TO_RIGHT() {
        return SDL_MESSAGEBOX_BUTTONS_LEFT_TO_RIGHT;
    }
    private static final int SDL_MESSAGEBOX_BUTTONS_RIGHT_TO_LEFT = (int)256L;
    /**
     * {@snippet lang=c :
     * #define SDL_MESSAGEBOX_BUTTONS_RIGHT_TO_LEFT 256
     * }
     */
    public static int SDL_MESSAGEBOX_BUTTONS_RIGHT_TO_LEFT() {
        return SDL_MESSAGEBOX_BUTTONS_RIGHT_TO_LEFT;
    }
    private static final int SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT 1
     * }
     */
    public static int SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT() {
        return SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT;
    }
    private static final int SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT 2
     * }
     */
    public static int SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT() {
        return SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_CREATE_ARGS_POINTER "SDL.process.create.args"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_CREATE_ARGS_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_CREATE_ARGS_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.create.args");
        }
        return Holder.SDL_PROP_PROCESS_CREATE_ARGS_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_CREATE_ENVIRONMENT_POINTER "SDL.process.create.environment"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_CREATE_ENVIRONMENT_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_CREATE_ENVIRONMENT_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.create.environment");
        }
        return Holder.SDL_PROP_PROCESS_CREATE_ENVIRONMENT_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_CREATE_WORKING_DIRECTORY_STRING "SDL.process.create.working_directory"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_CREATE_WORKING_DIRECTORY_STRING() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_CREATE_WORKING_DIRECTORY_STRING
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.create.working_directory");
        }
        return Holder.SDL_PROP_PROCESS_CREATE_WORKING_DIRECTORY_STRING;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_CREATE_STDIN_NUMBER "SDL.process.create.stdin_option"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_CREATE_STDIN_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_CREATE_STDIN_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.create.stdin_option");
        }
        return Holder.SDL_PROP_PROCESS_CREATE_STDIN_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_CREATE_STDIN_POINTER "SDL.process.create.stdin_source"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_CREATE_STDIN_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_CREATE_STDIN_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.create.stdin_source");
        }
        return Holder.SDL_PROP_PROCESS_CREATE_STDIN_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER "SDL.process.create.stdout_option"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.create.stdout_option");
        }
        return Holder.SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_CREATE_STDOUT_POINTER "SDL.process.create.stdout_source"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_CREATE_STDOUT_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_CREATE_STDOUT_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.create.stdout_source");
        }
        return Holder.SDL_PROP_PROCESS_CREATE_STDOUT_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_CREATE_STDERR_NUMBER "SDL.process.create.stderr_option"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_CREATE_STDERR_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_CREATE_STDERR_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.create.stderr_option");
        }
        return Holder.SDL_PROP_PROCESS_CREATE_STDERR_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_CREATE_STDERR_POINTER "SDL.process.create.stderr_source"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_CREATE_STDERR_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_CREATE_STDERR_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.create.stderr_source");
        }
        return Holder.SDL_PROP_PROCESS_CREATE_STDERR_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_CREATE_STDERR_TO_STDOUT_BOOLEAN "SDL.process.create.stderr_to_stdout"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_CREATE_STDERR_TO_STDOUT_BOOLEAN() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_CREATE_STDERR_TO_STDOUT_BOOLEAN
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.create.stderr_to_stdout");
        }
        return Holder.SDL_PROP_PROCESS_CREATE_STDERR_TO_STDOUT_BOOLEAN;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_CREATE_BACKGROUND_BOOLEAN "SDL.process.create.background"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_CREATE_BACKGROUND_BOOLEAN() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_CREATE_BACKGROUND_BOOLEAN
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.create.background");
        }
        return Holder.SDL_PROP_PROCESS_CREATE_BACKGROUND_BOOLEAN;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_PID_NUMBER "SDL.process.pid"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_PID_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_PID_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.pid");
        }
        return Holder.SDL_PROP_PROCESS_PID_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_STDIN_POINTER "SDL.process.stdin"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_STDIN_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_STDIN_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.stdin");
        }
        return Holder.SDL_PROP_PROCESS_STDIN_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_STDOUT_POINTER "SDL.process.stdout"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_STDOUT_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_STDOUT_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.stdout");
        }
        return Holder.SDL_PROP_PROCESS_STDOUT_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_STDERR_POINTER "SDL.process.stderr"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_STDERR_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_STDERR_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.stderr");
        }
        return Holder.SDL_PROP_PROCESS_STDERR_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_PROCESS_BACKGROUND_BOOLEAN "SDL.process.background"
     * }
     */
    public static MemorySegment SDL_PROP_PROCESS_BACKGROUND_BOOLEAN() {
        class Holder {
            static final MemorySegment SDL_PROP_PROCESS_BACKGROUND_BOOLEAN
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.process.background");
        }
        return Holder.SDL_PROP_PROCESS_BACKGROUND_BOOLEAN;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_SOFTWARE_RENDERER "software"
     * }
     */
    public static MemorySegment SDL_SOFTWARE_RENDERER() {
        class Holder {
            static final MemorySegment SDL_SOFTWARE_RENDERER
                = SDL.LIBRARY_ARENA.allocateFrom("software");
        }
        return Holder.SDL_SOFTWARE_RENDERER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_CREATE_NAME_STRING "SDL.renderer.create.name"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_CREATE_NAME_STRING() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_CREATE_NAME_STRING
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.create.name");
        }
        return Holder.SDL_PROP_RENDERER_CREATE_NAME_STRING;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_CREATE_WINDOW_POINTER "SDL.renderer.create.window"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_CREATE_WINDOW_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_CREATE_WINDOW_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.create.window");
        }
        return Holder.SDL_PROP_RENDERER_CREATE_WINDOW_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_CREATE_SURFACE_POINTER "SDL.renderer.create.surface"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_CREATE_SURFACE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_CREATE_SURFACE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.create.surface");
        }
        return Holder.SDL_PROP_RENDERER_CREATE_SURFACE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_CREATE_OUTPUT_COLORSPACE_NUMBER "SDL.renderer.create.output_colorspace"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_CREATE_OUTPUT_COLORSPACE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_CREATE_OUTPUT_COLORSPACE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.create.output_colorspace");
        }
        return Holder.SDL_PROP_RENDERER_CREATE_OUTPUT_COLORSPACE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_CREATE_PRESENT_VSYNC_NUMBER "SDL.renderer.create.present_vsync"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_CREATE_PRESENT_VSYNC_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_CREATE_PRESENT_VSYNC_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.create.present_vsync");
        }
        return Holder.SDL_PROP_RENDERER_CREATE_PRESENT_VSYNC_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_CREATE_VULKAN_INSTANCE_POINTER "SDL.renderer.create.vulkan.instance"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_INSTANCE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_INSTANCE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.create.vulkan.instance");
        }
        return Holder.SDL_PROP_RENDERER_CREATE_VULKAN_INSTANCE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_CREATE_VULKAN_SURFACE_NUMBER "SDL.renderer.create.vulkan.surface"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_SURFACE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_SURFACE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.create.vulkan.surface");
        }
        return Holder.SDL_PROP_RENDERER_CREATE_VULKAN_SURFACE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_CREATE_VULKAN_PHYSICAL_DEVICE_POINTER "SDL.renderer.create.vulkan.physical_device"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_PHYSICAL_DEVICE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_PHYSICAL_DEVICE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.create.vulkan.physical_device");
        }
        return Holder.SDL_PROP_RENDERER_CREATE_VULKAN_PHYSICAL_DEVICE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_CREATE_VULKAN_DEVICE_POINTER "SDL.renderer.create.vulkan.device"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_DEVICE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_DEVICE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.create.vulkan.device");
        }
        return Holder.SDL_PROP_RENDERER_CREATE_VULKAN_DEVICE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_CREATE_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER "SDL.renderer.create.vulkan.graphics_queue_family_index"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.create.vulkan.graphics_queue_family_index");
        }
        return Holder.SDL_PROP_RENDERER_CREATE_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_CREATE_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER "SDL.renderer.create.vulkan.present_queue_family_index"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_CREATE_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.create.vulkan.present_queue_family_index");
        }
        return Holder.SDL_PROP_RENDERER_CREATE_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_NAME_STRING "SDL.renderer.name"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_NAME_STRING() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_NAME_STRING
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.name");
        }
        return Holder.SDL_PROP_RENDERER_NAME_STRING;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_WINDOW_POINTER "SDL.renderer.window"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_WINDOW_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_WINDOW_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.window");
        }
        return Holder.SDL_PROP_RENDERER_WINDOW_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_SURFACE_POINTER "SDL.renderer.surface"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_SURFACE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_SURFACE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.surface");
        }
        return Holder.SDL_PROP_RENDERER_SURFACE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_VSYNC_NUMBER "SDL.renderer.vsync"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_VSYNC_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_VSYNC_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.vsync");
        }
        return Holder.SDL_PROP_RENDERER_VSYNC_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER "SDL.renderer.max_texture_size"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.max_texture_size");
        }
        return Holder.SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER "SDL.renderer.texture_formats"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.texture_formats");
        }
        return Holder.SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_OUTPUT_COLORSPACE_NUMBER "SDL.renderer.output_colorspace"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_OUTPUT_COLORSPACE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_OUTPUT_COLORSPACE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.output_colorspace");
        }
        return Holder.SDL_PROP_RENDERER_OUTPUT_COLORSPACE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_HDR_ENABLED_BOOLEAN "SDL.renderer.HDR_enabled"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_HDR_ENABLED_BOOLEAN() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_HDR_ENABLED_BOOLEAN
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.HDR_enabled");
        }
        return Holder.SDL_PROP_RENDERER_HDR_ENABLED_BOOLEAN;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_SDR_WHITE_POINT_FLOAT "SDL.renderer.SDR_white_point"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_SDR_WHITE_POINT_FLOAT() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_SDR_WHITE_POINT_FLOAT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.SDR_white_point");
        }
        return Holder.SDL_PROP_RENDERER_SDR_WHITE_POINT_FLOAT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_HDR_HEADROOM_FLOAT "SDL.renderer.HDR_headroom"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_HDR_HEADROOM_FLOAT() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_HDR_HEADROOM_FLOAT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.HDR_headroom");
        }
        return Holder.SDL_PROP_RENDERER_HDR_HEADROOM_FLOAT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_D3D9_DEVICE_POINTER "SDL.renderer.d3d9.device"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_D3D9_DEVICE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_D3D9_DEVICE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.d3d9.device");
        }
        return Holder.SDL_PROP_RENDERER_D3D9_DEVICE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_D3D11_DEVICE_POINTER "SDL.renderer.d3d11.device"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_D3D11_DEVICE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_D3D11_DEVICE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.d3d11.device");
        }
        return Holder.SDL_PROP_RENDERER_D3D11_DEVICE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_D3D11_SWAPCHAIN_POINTER "SDL.renderer.d3d11.swap_chain"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_D3D11_SWAPCHAIN_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_D3D11_SWAPCHAIN_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.d3d11.swap_chain");
        }
        return Holder.SDL_PROP_RENDERER_D3D11_SWAPCHAIN_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_D3D12_DEVICE_POINTER "SDL.renderer.d3d12.device"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_D3D12_DEVICE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_D3D12_DEVICE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.d3d12.device");
        }
        return Holder.SDL_PROP_RENDERER_D3D12_DEVICE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_D3D12_SWAPCHAIN_POINTER "SDL.renderer.d3d12.swap_chain"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_D3D12_SWAPCHAIN_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_D3D12_SWAPCHAIN_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.d3d12.swap_chain");
        }
        return Holder.SDL_PROP_RENDERER_D3D12_SWAPCHAIN_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_D3D12_COMMAND_QUEUE_POINTER "SDL.renderer.d3d12.command_queue"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_D3D12_COMMAND_QUEUE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_D3D12_COMMAND_QUEUE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.d3d12.command_queue");
        }
        return Holder.SDL_PROP_RENDERER_D3D12_COMMAND_QUEUE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_VULKAN_INSTANCE_POINTER "SDL.renderer.vulkan.instance"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_VULKAN_INSTANCE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_VULKAN_INSTANCE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.vulkan.instance");
        }
        return Holder.SDL_PROP_RENDERER_VULKAN_INSTANCE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_VULKAN_SURFACE_NUMBER "SDL.renderer.vulkan.surface"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_VULKAN_SURFACE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_VULKAN_SURFACE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.vulkan.surface");
        }
        return Holder.SDL_PROP_RENDERER_VULKAN_SURFACE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_VULKAN_PHYSICAL_DEVICE_POINTER "SDL.renderer.vulkan.physical_device"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_VULKAN_PHYSICAL_DEVICE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_VULKAN_PHYSICAL_DEVICE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.vulkan.physical_device");
        }
        return Holder.SDL_PROP_RENDERER_VULKAN_PHYSICAL_DEVICE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_VULKAN_DEVICE_POINTER "SDL.renderer.vulkan.device"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_VULKAN_DEVICE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_VULKAN_DEVICE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.vulkan.device");
        }
        return Holder.SDL_PROP_RENDERER_VULKAN_DEVICE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER "SDL.renderer.vulkan.graphics_queue_family_index"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.vulkan.graphics_queue_family_index");
        }
        return Holder.SDL_PROP_RENDERER_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER "SDL.renderer.vulkan.present_queue_family_index"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.vulkan.present_queue_family_index");
        }
        return Holder.SDL_PROP_RENDERER_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_VULKAN_SWAPCHAIN_IMAGE_COUNT_NUMBER "SDL.renderer.vulkan.swapchain_image_count"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_VULKAN_SWAPCHAIN_IMAGE_COUNT_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_VULKAN_SWAPCHAIN_IMAGE_COUNT_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.vulkan.swapchain_image_count");
        }
        return Holder.SDL_PROP_RENDERER_VULKAN_SWAPCHAIN_IMAGE_COUNT_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_RENDERER_GPU_DEVICE_POINTER "SDL.renderer.gpu.device"
     * }
     */
    public static MemorySegment SDL_PROP_RENDERER_GPU_DEVICE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_RENDERER_GPU_DEVICE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.renderer.gpu.device");
        }
        return Holder.SDL_PROP_RENDERER_GPU_DEVICE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER "SDL.texture.create.colorspace"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.colorspace");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER "SDL.texture.create.format"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.format");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER "SDL.texture.create.access"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.access");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER "SDL.texture.create.width"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.width");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER "SDL.texture.create.height"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.height");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_SDR_WHITE_POINT_FLOAT "SDL.texture.create.SDR_white_point"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_SDR_WHITE_POINT_FLOAT() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_SDR_WHITE_POINT_FLOAT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.SDR_white_point");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_SDR_WHITE_POINT_FLOAT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_HDR_HEADROOM_FLOAT "SDL.texture.create.HDR_headroom"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_HDR_HEADROOM_FLOAT() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_HDR_HEADROOM_FLOAT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.HDR_headroom");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_HDR_HEADROOM_FLOAT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_POINTER "SDL.texture.create.d3d11.texture"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.d3d11.texture");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_U_POINTER "SDL.texture.create.d3d11.texture_u"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_U_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_U_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.d3d11.texture_u");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_U_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_V_POINTER "SDL.texture.create.d3d11.texture_v"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_V_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_V_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.d3d11.texture_v");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_V_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_POINTER "SDL.texture.create.d3d12.texture"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.d3d12.texture");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_U_POINTER "SDL.texture.create.d3d12.texture_u"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_U_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_U_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.d3d12.texture_u");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_U_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_V_POINTER "SDL.texture.create.d3d12.texture_v"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_V_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_V_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.d3d12.texture_v");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_V_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_METAL_PIXELBUFFER_POINTER "SDL.texture.create.metal.pixelbuffer"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_METAL_PIXELBUFFER_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_METAL_PIXELBUFFER_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.metal.pixelbuffer");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_METAL_PIXELBUFFER_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_NUMBER "SDL.texture.create.opengl.texture"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.opengl.texture");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_UV_NUMBER "SDL.texture.create.opengl.texture_uv"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_UV_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_UV_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.opengl.texture_uv");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_UV_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_U_NUMBER "SDL.texture.create.opengl.texture_u"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_U_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_U_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.opengl.texture_u");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_U_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_V_NUMBER "SDL.texture.create.opengl.texture_v"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_V_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_V_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.opengl.texture_v");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_V_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_NUMBER "SDL.texture.create.opengles2.texture"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.opengles2.texture");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_UV_NUMBER "SDL.texture.create.opengles2.texture_uv"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_UV_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_UV_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.opengles2.texture_uv");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_UV_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_U_NUMBER "SDL.texture.create.opengles2.texture_u"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_U_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_U_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.opengles2.texture_u");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_U_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_V_NUMBER "SDL.texture.create.opengles2.texture_v"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_V_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_V_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.opengles2.texture_v");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_V_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_CREATE_VULKAN_TEXTURE_NUMBER "SDL.texture.create.vulkan.texture"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_CREATE_VULKAN_TEXTURE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_CREATE_VULKAN_TEXTURE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.create.vulkan.texture");
        }
        return Holder.SDL_PROP_TEXTURE_CREATE_VULKAN_TEXTURE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_COLORSPACE_NUMBER "SDL.texture.colorspace"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_COLORSPACE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_COLORSPACE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.colorspace");
        }
        return Holder.SDL_PROP_TEXTURE_COLORSPACE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_FORMAT_NUMBER "SDL.texture.format"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_FORMAT_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_FORMAT_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.format");
        }
        return Holder.SDL_PROP_TEXTURE_FORMAT_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_ACCESS_NUMBER "SDL.texture.access"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_ACCESS_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_ACCESS_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.access");
        }
        return Holder.SDL_PROP_TEXTURE_ACCESS_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_WIDTH_NUMBER "SDL.texture.width"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_WIDTH_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_WIDTH_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.width");
        }
        return Holder.SDL_PROP_TEXTURE_WIDTH_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_HEIGHT_NUMBER "SDL.texture.height"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_HEIGHT_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_HEIGHT_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.height");
        }
        return Holder.SDL_PROP_TEXTURE_HEIGHT_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_SDR_WHITE_POINT_FLOAT "SDL.texture.SDR_white_point"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_SDR_WHITE_POINT_FLOAT() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_SDR_WHITE_POINT_FLOAT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.SDR_white_point");
        }
        return Holder.SDL_PROP_TEXTURE_SDR_WHITE_POINT_FLOAT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_HDR_HEADROOM_FLOAT "SDL.texture.HDR_headroom"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_HDR_HEADROOM_FLOAT() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_HDR_HEADROOM_FLOAT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.HDR_headroom");
        }
        return Holder.SDL_PROP_TEXTURE_HDR_HEADROOM_FLOAT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_D3D11_TEXTURE_POINTER "SDL.texture.d3d11.texture"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_D3D11_TEXTURE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_D3D11_TEXTURE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.d3d11.texture");
        }
        return Holder.SDL_PROP_TEXTURE_D3D11_TEXTURE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_D3D11_TEXTURE_U_POINTER "SDL.texture.d3d11.texture_u"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_D3D11_TEXTURE_U_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_D3D11_TEXTURE_U_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.d3d11.texture_u");
        }
        return Holder.SDL_PROP_TEXTURE_D3D11_TEXTURE_U_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_D3D11_TEXTURE_V_POINTER "SDL.texture.d3d11.texture_v"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_D3D11_TEXTURE_V_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_D3D11_TEXTURE_V_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.d3d11.texture_v");
        }
        return Holder.SDL_PROP_TEXTURE_D3D11_TEXTURE_V_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_D3D12_TEXTURE_POINTER "SDL.texture.d3d12.texture"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_D3D12_TEXTURE_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_D3D12_TEXTURE_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.d3d12.texture");
        }
        return Holder.SDL_PROP_TEXTURE_D3D12_TEXTURE_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_D3D12_TEXTURE_U_POINTER "SDL.texture.d3d12.texture_u"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_D3D12_TEXTURE_U_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_D3D12_TEXTURE_U_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.d3d12.texture_u");
        }
        return Holder.SDL_PROP_TEXTURE_D3D12_TEXTURE_U_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_D3D12_TEXTURE_V_POINTER "SDL.texture.d3d12.texture_v"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_D3D12_TEXTURE_V_POINTER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_D3D12_TEXTURE_V_POINTER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.d3d12.texture_v");
        }
        return Holder.SDL_PROP_TEXTURE_D3D12_TEXTURE_V_POINTER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGL_TEXTURE_NUMBER "SDL.texture.opengl.texture"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGL_TEXTURE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGL_TEXTURE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengl.texture");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGL_TEXTURE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGL_TEXTURE_UV_NUMBER "SDL.texture.opengl.texture_uv"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGL_TEXTURE_UV_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGL_TEXTURE_UV_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengl.texture_uv");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGL_TEXTURE_UV_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGL_TEXTURE_U_NUMBER "SDL.texture.opengl.texture_u"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGL_TEXTURE_U_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGL_TEXTURE_U_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengl.texture_u");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGL_TEXTURE_U_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGL_TEXTURE_V_NUMBER "SDL.texture.opengl.texture_v"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGL_TEXTURE_V_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGL_TEXTURE_V_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengl.texture_v");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGL_TEXTURE_V_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGL_TEXTURE_TARGET_NUMBER "SDL.texture.opengl.target"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGL_TEXTURE_TARGET_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGL_TEXTURE_TARGET_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengl.target");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGL_TEXTURE_TARGET_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGL_TEX_W_FLOAT "SDL.texture.opengl.tex_w"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGL_TEX_W_FLOAT() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGL_TEX_W_FLOAT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengl.tex_w");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGL_TEX_W_FLOAT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGL_TEX_H_FLOAT "SDL.texture.opengl.tex_h"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGL_TEX_H_FLOAT() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGL_TEX_H_FLOAT
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengl.tex_h");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGL_TEX_H_FLOAT;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_NUMBER "SDL.texture.opengles2.texture"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengles2.texture");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_UV_NUMBER "SDL.texture.opengles2.texture_uv"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_UV_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_UV_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengles2.texture_uv");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_UV_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_U_NUMBER "SDL.texture.opengles2.texture_u"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_U_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_U_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengles2.texture_u");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_U_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_V_NUMBER "SDL.texture.opengles2.texture_v"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_V_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_V_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengles2.texture_v");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_V_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_TARGET_NUMBER "SDL.texture.opengles2.target"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_TARGET_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_TARGET_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.opengles2.target");
        }
        return Holder.SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_TARGET_NUMBER;
    }
    /**
     * {@snippet lang=c :
     * #define SDL_PROP_TEXTURE_VULKAN_TEXTURE_NUMBER "SDL.texture.vulkan.texture"
     * }
     */
    public static MemorySegment SDL_PROP_TEXTURE_VULKAN_TEXTURE_NUMBER() {
        class Holder {
            static final MemorySegment SDL_PROP_TEXTURE_VULKAN_TEXTURE_NUMBER
                = SDL.LIBRARY_ARENA.allocateFrom("SDL.texture.vulkan.texture");
        }
        return Holder.SDL_PROP_TEXTURE_VULKAN_TEXTURE_NUMBER;
    }
    private static final int SDL_RENDERER_VSYNC_ADAPTIVE = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define SDL_RENDERER_VSYNC_ADAPTIVE -1
     * }
     */
    public static int SDL_RENDERER_VSYNC_ADAPTIVE() {
        return SDL_RENDERER_VSYNC_ADAPTIVE;
    }
    private static final long SDL_NS_PER_SECOND = 1000000000L;
    /**
     * {@snippet lang=c :
     * #define SDL_NS_PER_SECOND 1000000000
     * }
     */
    public static long SDL_NS_PER_SECOND() {
        return SDL_NS_PER_SECOND;
    }
    private static final int SDL_TRAYENTRY_BUTTON = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SDL_TRAYENTRY_BUTTON 1
     * }
     */
    public static int SDL_TRAYENTRY_BUTTON() {
        return SDL_TRAYENTRY_BUTTON;
    }
    private static final int SDL_TRAYENTRY_CHECKBOX = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SDL_TRAYENTRY_CHECKBOX 2
     * }
     */
    public static int SDL_TRAYENTRY_CHECKBOX() {
        return SDL_TRAYENTRY_CHECKBOX;
    }
    private static final int SDL_TRAYENTRY_SUBMENU = (int)4L;
    /**
     * {@snippet lang=c :
     * #define SDL_TRAYENTRY_SUBMENU 4
     * }
     */
    public static int SDL_TRAYENTRY_SUBMENU() {
        return SDL_TRAYENTRY_SUBMENU;
    }
    private static final int SDL_TRAYENTRY_DISABLED = (int)2147483648L;
    /**
     * {@snippet lang=c :
     * #define SDL_TRAYENTRY_DISABLED 2147483648
     * }
     */
    public static int SDL_TRAYENTRY_DISABLED() {
        return SDL_TRAYENTRY_DISABLED;
    }
    private static final int SDL_TRAYENTRY_CHECKED = (int)1073741824L;
    /**
     * {@snippet lang=c :
     * #define SDL_TRAYENTRY_CHECKED 1073741824
     * }
     */
    public static int SDL_TRAYENTRY_CHECKED() {
        return SDL_TRAYENTRY_CHECKED;
    }
    private static final int SDL_VERSION = (int)3003000L;
    /**
     * {@snippet lang=c :
     * #define SDL_VERSION 3003000
     * }
     */
    public static int SDL_VERSION() {
        return SDL_VERSION;
    }
}

