// Generated by jextract

package org.sdl3;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_VirtualJoystickDesc {
 *     Uint32 version;
 *     Uint16 type;
 *     Uint16 padding;
 *     Uint16 vendor_id;
 *     Uint16 product_id;
 *     Uint16 naxes;
 *     Uint16 nbuttons;
 *     Uint16 nballs;
 *     Uint16 nhats;
 *     Uint16 ntouchpads;
 *     Uint16 nsensors;
 *     Uint16 padding2[2];
 *     Uint32 button_mask;
 *     Uint32 axis_mask;
 *     const char *name;
 *     const SDL_VirtualJoystickTouchpadDesc *touchpads;
 *     const SDL_VirtualJoystickSensorDesc *sensors;
 *     void *userdata;
 *     void (*Update)(void *) __attribute__((cdecl));
 *     void (*SetPlayerIndex)(void *, int) __attribute__((cdecl));
 *     bool (*Rumble)(void *, Uint16, Uint16) __attribute__((cdecl));
 *     bool (*RumbleTriggers)(void *, Uint16, Uint16) __attribute__((cdecl));
 *     bool (*SetLED)(void *, Uint8, Uint8, Uint8) __attribute__((cdecl));
 *     bool (*SendEffect)(void *, const void *, int) __attribute__((cdecl));
 *     bool (*SetSensorsEnabled)(void *, bool) __attribute__((cdecl));
 *     void (*Cleanup)(void *) __attribute__((cdecl));
 * }
 * }
 */
public class SDL_VirtualJoystickDesc {

    SDL_VirtualJoystickDesc() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL.C_INT.withName("version"),
        SDL.C_SHORT.withName("type"),
        SDL.C_SHORT.withName("padding"),
        SDL.C_SHORT.withName("vendor_id"),
        SDL.C_SHORT.withName("product_id"),
        SDL.C_SHORT.withName("naxes"),
        SDL.C_SHORT.withName("nbuttons"),
        SDL.C_SHORT.withName("nballs"),
        SDL.C_SHORT.withName("nhats"),
        SDL.C_SHORT.withName("ntouchpads"),
        SDL.C_SHORT.withName("nsensors"),
        MemoryLayout.sequenceLayout(2, SDL.C_SHORT).withName("padding2"),
        SDL.C_INT.withName("button_mask"),
        SDL.C_INT.withName("axis_mask"),
        MemoryLayout.paddingLayout(4),
        SDL.C_POINTER.withName("name"),
        SDL.C_POINTER.withName("touchpads"),
        SDL.C_POINTER.withName("sensors"),
        SDL.C_POINTER.withName("userdata"),
        SDL.C_POINTER.withName("Update"),
        SDL.C_POINTER.withName("SetPlayerIndex"),
        SDL.C_POINTER.withName("Rumble"),
        SDL.C_POINTER.withName("RumbleTriggers"),
        SDL.C_POINTER.withName("SetLED"),
        SDL.C_POINTER.withName("SendEffect"),
        SDL.C_POINTER.withName("SetSensorsEnabled"),
        SDL.C_POINTER.withName("Cleanup")
    ).withName("SDL_VirtualJoystickDesc");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt version$LAYOUT = (OfInt)$LAYOUT.select(groupElement("version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static final OfInt version$layout() {
        return version$LAYOUT;
    }

    private static final long version$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static final long version$offset() {
        return version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static int version(MemorySegment struct) {
        return struct.get(version$LAYOUT, version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static void version(MemorySegment struct, int fieldValue) {
        struct.set(version$LAYOUT, version$OFFSET, fieldValue);
    }

    private static final OfShort type$LAYOUT = (OfShort)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 type
     * }
     */
    public static final OfShort type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 type
     * }
     */
    public static short type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 type
     * }
     */
    public static void type(MemorySegment struct, short fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfShort padding$LAYOUT = (OfShort)$LAYOUT.select(groupElement("padding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 padding
     * }
     */
    public static final OfShort padding$layout() {
        return padding$LAYOUT;
    }

    private static final long padding$OFFSET = 6;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 padding
     * }
     */
    public static final long padding$offset() {
        return padding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 padding
     * }
     */
    public static short padding(MemorySegment struct) {
        return struct.get(padding$LAYOUT, padding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 padding
     * }
     */
    public static void padding(MemorySegment struct, short fieldValue) {
        struct.set(padding$LAYOUT, padding$OFFSET, fieldValue);
    }

    private static final OfShort vendor_id$LAYOUT = (OfShort)$LAYOUT.select(groupElement("vendor_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 vendor_id
     * }
     */
    public static final OfShort vendor_id$layout() {
        return vendor_id$LAYOUT;
    }

    private static final long vendor_id$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 vendor_id
     * }
     */
    public static final long vendor_id$offset() {
        return vendor_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 vendor_id
     * }
     */
    public static short vendor_id(MemorySegment struct) {
        return struct.get(vendor_id$LAYOUT, vendor_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 vendor_id
     * }
     */
    public static void vendor_id(MemorySegment struct, short fieldValue) {
        struct.set(vendor_id$LAYOUT, vendor_id$OFFSET, fieldValue);
    }

    private static final OfShort product_id$LAYOUT = (OfShort)$LAYOUT.select(groupElement("product_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 product_id
     * }
     */
    public static final OfShort product_id$layout() {
        return product_id$LAYOUT;
    }

    private static final long product_id$OFFSET = 10;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 product_id
     * }
     */
    public static final long product_id$offset() {
        return product_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 product_id
     * }
     */
    public static short product_id(MemorySegment struct) {
        return struct.get(product_id$LAYOUT, product_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 product_id
     * }
     */
    public static void product_id(MemorySegment struct, short fieldValue) {
        struct.set(product_id$LAYOUT, product_id$OFFSET, fieldValue);
    }

    private static final OfShort naxes$LAYOUT = (OfShort)$LAYOUT.select(groupElement("naxes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 naxes
     * }
     */
    public static final OfShort naxes$layout() {
        return naxes$LAYOUT;
    }

    private static final long naxes$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 naxes
     * }
     */
    public static final long naxes$offset() {
        return naxes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 naxes
     * }
     */
    public static short naxes(MemorySegment struct) {
        return struct.get(naxes$LAYOUT, naxes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 naxes
     * }
     */
    public static void naxes(MemorySegment struct, short fieldValue) {
        struct.set(naxes$LAYOUT, naxes$OFFSET, fieldValue);
    }

    private static final OfShort nbuttons$LAYOUT = (OfShort)$LAYOUT.select(groupElement("nbuttons"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 nbuttons
     * }
     */
    public static final OfShort nbuttons$layout() {
        return nbuttons$LAYOUT;
    }

    private static final long nbuttons$OFFSET = 14;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 nbuttons
     * }
     */
    public static final long nbuttons$offset() {
        return nbuttons$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 nbuttons
     * }
     */
    public static short nbuttons(MemorySegment struct) {
        return struct.get(nbuttons$LAYOUT, nbuttons$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 nbuttons
     * }
     */
    public static void nbuttons(MemorySegment struct, short fieldValue) {
        struct.set(nbuttons$LAYOUT, nbuttons$OFFSET, fieldValue);
    }

    private static final OfShort nballs$LAYOUT = (OfShort)$LAYOUT.select(groupElement("nballs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 nballs
     * }
     */
    public static final OfShort nballs$layout() {
        return nballs$LAYOUT;
    }

    private static final long nballs$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 nballs
     * }
     */
    public static final long nballs$offset() {
        return nballs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 nballs
     * }
     */
    public static short nballs(MemorySegment struct) {
        return struct.get(nballs$LAYOUT, nballs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 nballs
     * }
     */
    public static void nballs(MemorySegment struct, short fieldValue) {
        struct.set(nballs$LAYOUT, nballs$OFFSET, fieldValue);
    }

    private static final OfShort nhats$LAYOUT = (OfShort)$LAYOUT.select(groupElement("nhats"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 nhats
     * }
     */
    public static final OfShort nhats$layout() {
        return nhats$LAYOUT;
    }

    private static final long nhats$OFFSET = 18;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 nhats
     * }
     */
    public static final long nhats$offset() {
        return nhats$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 nhats
     * }
     */
    public static short nhats(MemorySegment struct) {
        return struct.get(nhats$LAYOUT, nhats$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 nhats
     * }
     */
    public static void nhats(MemorySegment struct, short fieldValue) {
        struct.set(nhats$LAYOUT, nhats$OFFSET, fieldValue);
    }

    private static final OfShort ntouchpads$LAYOUT = (OfShort)$LAYOUT.select(groupElement("ntouchpads"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 ntouchpads
     * }
     */
    public static final OfShort ntouchpads$layout() {
        return ntouchpads$LAYOUT;
    }

    private static final long ntouchpads$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 ntouchpads
     * }
     */
    public static final long ntouchpads$offset() {
        return ntouchpads$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 ntouchpads
     * }
     */
    public static short ntouchpads(MemorySegment struct) {
        return struct.get(ntouchpads$LAYOUT, ntouchpads$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 ntouchpads
     * }
     */
    public static void ntouchpads(MemorySegment struct, short fieldValue) {
        struct.set(ntouchpads$LAYOUT, ntouchpads$OFFSET, fieldValue);
    }

    private static final OfShort nsensors$LAYOUT = (OfShort)$LAYOUT.select(groupElement("nsensors"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 nsensors
     * }
     */
    public static final OfShort nsensors$layout() {
        return nsensors$LAYOUT;
    }

    private static final long nsensors$OFFSET = 22;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 nsensors
     * }
     */
    public static final long nsensors$offset() {
        return nsensors$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 nsensors
     * }
     */
    public static short nsensors(MemorySegment struct) {
        return struct.get(nsensors$LAYOUT, nsensors$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 nsensors
     * }
     */
    public static void nsensors(MemorySegment struct, short fieldValue) {
        struct.set(nsensors$LAYOUT, nsensors$OFFSET, fieldValue);
    }

    private static final SequenceLayout padding2$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("padding2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 padding2[2]
     * }
     */
    public static final SequenceLayout padding2$layout() {
        return padding2$LAYOUT;
    }

    private static final long padding2$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 padding2[2]
     * }
     */
    public static final long padding2$offset() {
        return padding2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 padding2[2]
     * }
     */
    public static MemorySegment padding2(MemorySegment struct) {
        return struct.asSlice(padding2$OFFSET, padding2$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 padding2[2]
     * }
     */
    public static void padding2(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, padding2$OFFSET, padding2$LAYOUT.byteSize());
    }

    private static long[] padding2$DIMS = { 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * Uint16 padding2[2]
     * }
     */
    public static long[] padding2$dimensions() {
        return padding2$DIMS;
    }
    private static final VarHandle padding2$ELEM_HANDLE = padding2$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * Uint16 padding2[2]
     * }
     */
    public static short padding2(MemorySegment struct, long index0) {
        return (short)padding2$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * Uint16 padding2[2]
     * }
     */
    public static void padding2(MemorySegment struct, long index0, short fieldValue) {
        padding2$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfInt button_mask$LAYOUT = (OfInt)$LAYOUT.select(groupElement("button_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 button_mask
     * }
     */
    public static final OfInt button_mask$layout() {
        return button_mask$LAYOUT;
    }

    private static final long button_mask$OFFSET = 28;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 button_mask
     * }
     */
    public static final long button_mask$offset() {
        return button_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 button_mask
     * }
     */
    public static int button_mask(MemorySegment struct) {
        return struct.get(button_mask$LAYOUT, button_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 button_mask
     * }
     */
    public static void button_mask(MemorySegment struct, int fieldValue) {
        struct.set(button_mask$LAYOUT, button_mask$OFFSET, fieldValue);
    }

    private static final OfInt axis_mask$LAYOUT = (OfInt)$LAYOUT.select(groupElement("axis_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 axis_mask
     * }
     */
    public static final OfInt axis_mask$layout() {
        return axis_mask$LAYOUT;
    }

    private static final long axis_mask$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 axis_mask
     * }
     */
    public static final long axis_mask$offset() {
        return axis_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 axis_mask
     * }
     */
    public static int axis_mask(MemorySegment struct) {
        return struct.get(axis_mask$LAYOUT, axis_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 axis_mask
     * }
     */
    public static void axis_mask(MemorySegment struct, int fieldValue) {
        struct.set(axis_mask$LAYOUT, axis_mask$OFFSET, fieldValue);
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final AddressLayout touchpads$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("touchpads"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const SDL_VirtualJoystickTouchpadDesc *touchpads
     * }
     */
    public static final AddressLayout touchpads$layout() {
        return touchpads$LAYOUT;
    }

    private static final long touchpads$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const SDL_VirtualJoystickTouchpadDesc *touchpads
     * }
     */
    public static final long touchpads$offset() {
        return touchpads$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const SDL_VirtualJoystickTouchpadDesc *touchpads
     * }
     */
    public static MemorySegment touchpads(MemorySegment struct) {
        return struct.get(touchpads$LAYOUT, touchpads$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const SDL_VirtualJoystickTouchpadDesc *touchpads
     * }
     */
    public static void touchpads(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(touchpads$LAYOUT, touchpads$OFFSET, fieldValue);
    }

    private static final AddressLayout sensors$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sensors"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const SDL_VirtualJoystickSensorDesc *sensors
     * }
     */
    public static final AddressLayout sensors$layout() {
        return sensors$LAYOUT;
    }

    private static final long sensors$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const SDL_VirtualJoystickSensorDesc *sensors
     * }
     */
    public static final long sensors$offset() {
        return sensors$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const SDL_VirtualJoystickSensorDesc *sensors
     * }
     */
    public static MemorySegment sensors(MemorySegment struct) {
        return struct.get(sensors$LAYOUT, sensors$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const SDL_VirtualJoystickSensorDesc *sensors
     * }
     */
    public static void sensors(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(sensors$LAYOUT, sensors$OFFSET, fieldValue);
    }

    private static final AddressLayout userdata$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("userdata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static final AddressLayout userdata$layout() {
        return userdata$LAYOUT;
    }

    private static final long userdata$OFFSET = 64;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static final long userdata$offset() {
        return userdata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static MemorySegment userdata(MemorySegment struct) {
        return struct.get(userdata$LAYOUT, userdata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static void userdata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(userdata$LAYOUT, userdata$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*Update)(void *) __attribute__((cdecl))
     * }
     */
    public static class Update {

        Update() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            SDL.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(Update.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Update.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Update$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Update"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*Update)(void *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout Update$layout() {
        return Update$LAYOUT;
    }

    private static final long Update$OFFSET = 72;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*Update)(void *) __attribute__((cdecl))
     * }
     */
    public static final long Update$offset() {
        return Update$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*Update)(void *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment Update(MemorySegment struct) {
        return struct.get(Update$LAYOUT, Update$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*Update)(void *) __attribute__((cdecl))
     * }
     */
    public static void Update(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Update$LAYOUT, Update$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*SetPlayerIndex)(void *, int) __attribute__((cdecl))
     * }
     */
    public static class SetPlayerIndex {

        SetPlayerIndex() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            SDL.C_POINTER,
            SDL.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(SetPlayerIndex.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetPlayerIndex.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, int _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetPlayerIndex$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetPlayerIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*SetPlayerIndex)(void *, int) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout SetPlayerIndex$layout() {
        return SetPlayerIndex$LAYOUT;
    }

    private static final long SetPlayerIndex$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*SetPlayerIndex)(void *, int) __attribute__((cdecl))
     * }
     */
    public static final long SetPlayerIndex$offset() {
        return SetPlayerIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*SetPlayerIndex)(void *, int) __attribute__((cdecl))
     * }
     */
    public static MemorySegment SetPlayerIndex(MemorySegment struct) {
        return struct.get(SetPlayerIndex$LAYOUT, SetPlayerIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*SetPlayerIndex)(void *, int) __attribute__((cdecl))
     * }
     */
    public static void SetPlayerIndex(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetPlayerIndex$LAYOUT, SetPlayerIndex$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*Rumble)(void *, Uint16, Uint16) __attribute__((cdecl))
     * }
     */
    public static class Rumble {

        Rumble() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, short _x1, short _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_SHORT,
            SDL.C_SHORT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(Rumble.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Rumble.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, short _x1, short _x2) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Rumble$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Rumble"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*Rumble)(void *, Uint16, Uint16) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout Rumble$layout() {
        return Rumble$LAYOUT;
    }

    private static final long Rumble$OFFSET = 88;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*Rumble)(void *, Uint16, Uint16) __attribute__((cdecl))
     * }
     */
    public static final long Rumble$offset() {
        return Rumble$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*Rumble)(void *, Uint16, Uint16) __attribute__((cdecl))
     * }
     */
    public static MemorySegment Rumble(MemorySegment struct) {
        return struct.get(Rumble$LAYOUT, Rumble$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*Rumble)(void *, Uint16, Uint16) __attribute__((cdecl))
     * }
     */
    public static void Rumble(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Rumble$LAYOUT, Rumble$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*RumbleTriggers)(void *, Uint16, Uint16) __attribute__((cdecl))
     * }
     */
    public static class RumbleTriggers {

        RumbleTriggers() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, short _x1, short _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_SHORT,
            SDL.C_SHORT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(RumbleTriggers.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(RumbleTriggers.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, short _x1, short _x2) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout RumbleTriggers$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("RumbleTriggers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*RumbleTriggers)(void *, Uint16, Uint16) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout RumbleTriggers$layout() {
        return RumbleTriggers$LAYOUT;
    }

    private static final long RumbleTriggers$OFFSET = 96;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*RumbleTriggers)(void *, Uint16, Uint16) __attribute__((cdecl))
     * }
     */
    public static final long RumbleTriggers$offset() {
        return RumbleTriggers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*RumbleTriggers)(void *, Uint16, Uint16) __attribute__((cdecl))
     * }
     */
    public static MemorySegment RumbleTriggers(MemorySegment struct) {
        return struct.get(RumbleTriggers$LAYOUT, RumbleTriggers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*RumbleTriggers)(void *, Uint16, Uint16) __attribute__((cdecl))
     * }
     */
    public static void RumbleTriggers(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(RumbleTriggers$LAYOUT, RumbleTriggers$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*SetLED)(void *, Uint8, Uint8, Uint8) __attribute__((cdecl))
     * }
     */
    public static class SetLED {

        SetLED() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, byte _x1, byte _x2, byte _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_CHAR,
            SDL.C_CHAR,
            SDL.C_CHAR
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(SetLED.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetLED.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, byte _x1, byte _x2, byte _x3) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetLED$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetLED"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*SetLED)(void *, Uint8, Uint8, Uint8) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout SetLED$layout() {
        return SetLED$LAYOUT;
    }

    private static final long SetLED$OFFSET = 104;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*SetLED)(void *, Uint8, Uint8, Uint8) __attribute__((cdecl))
     * }
     */
    public static final long SetLED$offset() {
        return SetLED$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*SetLED)(void *, Uint8, Uint8, Uint8) __attribute__((cdecl))
     * }
     */
    public static MemorySegment SetLED(MemorySegment struct) {
        return struct.get(SetLED$LAYOUT, SetLED$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*SetLED)(void *, Uint8, Uint8, Uint8) __attribute__((cdecl))
     * }
     */
    public static void SetLED(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetLED$LAYOUT, SetLED$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*SendEffect)(void *, const void *, int) __attribute__((cdecl))
     * }
     */
    public static class SendEffect {

        SendEffect() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1, int _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_POINTER,
            SDL.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(SendEffect.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SendEffect.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, int _x2) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SendEffect$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SendEffect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*SendEffect)(void *, const void *, int) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout SendEffect$layout() {
        return SendEffect$LAYOUT;
    }

    private static final long SendEffect$OFFSET = 112;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*SendEffect)(void *, const void *, int) __attribute__((cdecl))
     * }
     */
    public static final long SendEffect$offset() {
        return SendEffect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*SendEffect)(void *, const void *, int) __attribute__((cdecl))
     * }
     */
    public static MemorySegment SendEffect(MemorySegment struct) {
        return struct.get(SendEffect$LAYOUT, SendEffect$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*SendEffect)(void *, const void *, int) __attribute__((cdecl))
     * }
     */
    public static void SendEffect(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SendEffect$LAYOUT, SendEffect$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*SetSensorsEnabled)(void *, bool) __attribute__((cdecl))
     * }
     */
    public static class SetSensorsEnabled {

        SetSensorsEnabled() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, boolean _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_BOOL
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(SetSensorsEnabled.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetSensorsEnabled.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, boolean _x1) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetSensorsEnabled$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetSensorsEnabled"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*SetSensorsEnabled)(void *, bool) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout SetSensorsEnabled$layout() {
        return SetSensorsEnabled$LAYOUT;
    }

    private static final long SetSensorsEnabled$OFFSET = 120;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*SetSensorsEnabled)(void *, bool) __attribute__((cdecl))
     * }
     */
    public static final long SetSensorsEnabled$offset() {
        return SetSensorsEnabled$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*SetSensorsEnabled)(void *, bool) __attribute__((cdecl))
     * }
     */
    public static MemorySegment SetSensorsEnabled(MemorySegment struct) {
        return struct.get(SetSensorsEnabled$LAYOUT, SetSensorsEnabled$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*SetSensorsEnabled)(void *, bool) __attribute__((cdecl))
     * }
     */
    public static void SetSensorsEnabled(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetSensorsEnabled$LAYOUT, SetSensorsEnabled$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*Cleanup)(void *) __attribute__((cdecl))
     * }
     */
    public static class Cleanup {

        Cleanup() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            SDL.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(Cleanup.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Cleanup.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Cleanup$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Cleanup"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*Cleanup)(void *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout Cleanup$layout() {
        return Cleanup$LAYOUT;
    }

    private static final long Cleanup$OFFSET = 128;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*Cleanup)(void *) __attribute__((cdecl))
     * }
     */
    public static final long Cleanup$offset() {
        return Cleanup$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*Cleanup)(void *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment Cleanup(MemorySegment struct) {
        return struct.get(Cleanup$LAYOUT, Cleanup$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*Cleanup)(void *) __attribute__((cdecl))
     * }
     */
    public static void Cleanup(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Cleanup$LAYOUT, Cleanup$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

