// Generated by jextract

package org.sdl3;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_StorageInterface {
 *     Uint32 version;
 *     bool (*close)(void *) __attribute__((cdecl));
 *     bool (*ready)(void *) __attribute__((cdecl));
 *     bool (*enumerate)(void *, const char *, SDL_EnumerateDirectoryCallback, void *) __attribute__((cdecl));
 *     bool (*info)(void *, const char *, SDL_PathInfo *) __attribute__((cdecl));
 *     bool (*read_file)(void *, const char *, void *, Uint64) __attribute__((cdecl));
 *     bool (*write_file)(void *, const char *, const void *, Uint64) __attribute__((cdecl));
 *     bool (*mkdir)(void *, const char *) __attribute__((cdecl));
 *     bool (*remove)(void *, const char *) __attribute__((cdecl));
 *     bool (*rename)(void *, const char *, const char *) __attribute__((cdecl));
 *     bool (*copy)(void *, const char *, const char *) __attribute__((cdecl));
 *     Uint64 (*space_remaining)(void *) __attribute__((cdecl));
 * }
 * }
 */
public class SDL_StorageInterface {

    SDL_StorageInterface() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL.C_INT.withName("version"),
        MemoryLayout.paddingLayout(4),
        SDL.C_POINTER.withName("close"),
        SDL.C_POINTER.withName("ready"),
        SDL.C_POINTER.withName("enumerate"),
        SDL.C_POINTER.withName("info"),
        SDL.C_POINTER.withName("read_file"),
        SDL.C_POINTER.withName("write_file"),
        SDL.C_POINTER.withName("mkdir"),
        SDL.C_POINTER.withName("remove"),
        SDL.C_POINTER.withName("rename"),
        SDL.C_POINTER.withName("copy"),
        SDL.C_POINTER.withName("space_remaining")
    ).withName("SDL_StorageInterface");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt version$LAYOUT = (OfInt)$LAYOUT.select(groupElement("version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static final OfInt version$layout() {
        return version$LAYOUT;
    }

    private static final long version$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static final long version$offset() {
        return version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static int version(MemorySegment struct) {
        return struct.get(version$LAYOUT, version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static void version(MemorySegment struct, int fieldValue) {
        struct.set(version$LAYOUT, version$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*close)(void *) __attribute__((cdecl))
     * }
     */
    public static class close {

        close() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(close.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(close.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout close$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("close"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*close)(void *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout close$layout() {
        return close$LAYOUT;
    }

    private static final long close$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*close)(void *) __attribute__((cdecl))
     * }
     */
    public static final long close$offset() {
        return close$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*close)(void *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment close(MemorySegment struct) {
        return struct.get(close$LAYOUT, close$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*close)(void *) __attribute__((cdecl))
     * }
     */
    public static void close(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(close$LAYOUT, close$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*ready)(void *) __attribute__((cdecl))
     * }
     */
    public static class ready {

        ready() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(ready.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ready.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ready$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ready"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*ready)(void *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout ready$layout() {
        return ready$LAYOUT;
    }

    private static final long ready$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*ready)(void *) __attribute__((cdecl))
     * }
     */
    public static final long ready$offset() {
        return ready$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*ready)(void *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment ready(MemorySegment struct) {
        return struct.get(ready$LAYOUT, ready$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*ready)(void *) __attribute__((cdecl))
     * }
     */
    public static void ready(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ready$LAYOUT, ready$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*enumerate)(void *, const char *, SDL_EnumerateDirectoryCallback, void *) __attribute__((cdecl))
     * }
     */
    public static class enumerate {

        enumerate() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_POINTER,
            SDL.C_POINTER,
            SDL.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(enumerate.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(enumerate.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout enumerate$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("enumerate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*enumerate)(void *, const char *, SDL_EnumerateDirectoryCallback, void *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout enumerate$layout() {
        return enumerate$LAYOUT;
    }

    private static final long enumerate$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*enumerate)(void *, const char *, SDL_EnumerateDirectoryCallback, void *) __attribute__((cdecl))
     * }
     */
    public static final long enumerate$offset() {
        return enumerate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*enumerate)(void *, const char *, SDL_EnumerateDirectoryCallback, void *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment enumerate(MemorySegment struct) {
        return struct.get(enumerate$LAYOUT, enumerate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*enumerate)(void *, const char *, SDL_EnumerateDirectoryCallback, void *) __attribute__((cdecl))
     * }
     */
    public static void enumerate(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(enumerate$LAYOUT, enumerate$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*info)(void *, const char *, SDL_PathInfo *) __attribute__((cdecl))
     * }
     */
    public static class info {

        info() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_POINTER,
            SDL.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(info.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(info.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout info$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*info)(void *, const char *, SDL_PathInfo *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout info$layout() {
        return info$LAYOUT;
    }

    private static final long info$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*info)(void *, const char *, SDL_PathInfo *) __attribute__((cdecl))
     * }
     */
    public static final long info$offset() {
        return info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*info)(void *, const char *, SDL_PathInfo *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment info(MemorySegment struct) {
        return struct.get(info$LAYOUT, info$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*info)(void *, const char *, SDL_PathInfo *) __attribute__((cdecl))
     * }
     */
    public static void info(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(info$LAYOUT, info$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*read_file)(void *, const char *, void *, Uint64) __attribute__((cdecl))
     * }
     */
    public static class read_file {

        read_file() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_POINTER,
            SDL.C_POINTER,
            SDL.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(read_file.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(read_file.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout read_file$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("read_file"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*read_file)(void *, const char *, void *, Uint64) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout read_file$layout() {
        return read_file$LAYOUT;
    }

    private static final long read_file$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*read_file)(void *, const char *, void *, Uint64) __attribute__((cdecl))
     * }
     */
    public static final long read_file$offset() {
        return read_file$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*read_file)(void *, const char *, void *, Uint64) __attribute__((cdecl))
     * }
     */
    public static MemorySegment read_file(MemorySegment struct) {
        return struct.get(read_file$LAYOUT, read_file$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*read_file)(void *, const char *, void *, Uint64) __attribute__((cdecl))
     * }
     */
    public static void read_file(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(read_file$LAYOUT, read_file$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*write_file)(void *, const char *, const void *, Uint64) __attribute__((cdecl))
     * }
     */
    public static class write_file {

        write_file() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_POINTER,
            SDL.C_POINTER,
            SDL.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(write_file.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(write_file.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout write_file$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("write_file"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*write_file)(void *, const char *, const void *, Uint64) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout write_file$layout() {
        return write_file$LAYOUT;
    }

    private static final long write_file$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*write_file)(void *, const char *, const void *, Uint64) __attribute__((cdecl))
     * }
     */
    public static final long write_file$offset() {
        return write_file$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*write_file)(void *, const char *, const void *, Uint64) __attribute__((cdecl))
     * }
     */
    public static MemorySegment write_file(MemorySegment struct) {
        return struct.get(write_file$LAYOUT, write_file$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*write_file)(void *, const char *, const void *, Uint64) __attribute__((cdecl))
     * }
     */
    public static void write_file(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(write_file$LAYOUT, write_file$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*mkdir)(void *, const char *) __attribute__((cdecl))
     * }
     */
    public static class mkdir {

        mkdir() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(mkdir.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(mkdir.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout mkdir$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mkdir"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*mkdir)(void *, const char *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout mkdir$layout() {
        return mkdir$LAYOUT;
    }

    private static final long mkdir$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*mkdir)(void *, const char *) __attribute__((cdecl))
     * }
     */
    public static final long mkdir$offset() {
        return mkdir$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*mkdir)(void *, const char *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment mkdir(MemorySegment struct) {
        return struct.get(mkdir$LAYOUT, mkdir$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*mkdir)(void *, const char *) __attribute__((cdecl))
     * }
     */
    public static void mkdir(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mkdir$LAYOUT, mkdir$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*remove)(void *, const char *) __attribute__((cdecl))
     * }
     */
    public static class remove {

        remove() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(remove.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(remove.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout remove$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("remove"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*remove)(void *, const char *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout remove$layout() {
        return remove$LAYOUT;
    }

    private static final long remove$OFFSET = 64;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*remove)(void *, const char *) __attribute__((cdecl))
     * }
     */
    public static final long remove$offset() {
        return remove$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*remove)(void *, const char *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment remove(MemorySegment struct) {
        return struct.get(remove$LAYOUT, remove$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*remove)(void *, const char *) __attribute__((cdecl))
     * }
     */
    public static void remove(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(remove$LAYOUT, remove$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*rename)(void *, const char *, const char *) __attribute__((cdecl))
     * }
     */
    public static class rename {

        rename() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_POINTER,
            SDL.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(rename.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(rename.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout rename$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("rename"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*rename)(void *, const char *, const char *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout rename$layout() {
        return rename$LAYOUT;
    }

    private static final long rename$OFFSET = 72;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*rename)(void *, const char *, const char *) __attribute__((cdecl))
     * }
     */
    public static final long rename$offset() {
        return rename$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*rename)(void *, const char *, const char *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment rename(MemorySegment struct) {
        return struct.get(rename$LAYOUT, rename$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*rename)(void *, const char *, const char *) __attribute__((cdecl))
     * }
     */
    public static void rename(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(rename$LAYOUT, rename$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*copy)(void *, const char *, const char *) __attribute__((cdecl))
     * }
     */
    public static class copy {

        copy() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_BOOL,
            SDL.C_POINTER,
            SDL.C_POINTER,
            SDL.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(copy.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(copy.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout copy$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("copy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*copy)(void *, const char *, const char *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout copy$layout() {
        return copy$LAYOUT;
    }

    private static final long copy$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*copy)(void *, const char *, const char *) __attribute__((cdecl))
     * }
     */
    public static final long copy$offset() {
        return copy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*copy)(void *, const char *, const char *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment copy(MemorySegment struct) {
        return struct.get(copy$LAYOUT, copy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*copy)(void *, const char *, const char *) __attribute__((cdecl))
     * }
     */
    public static void copy(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(copy$LAYOUT, copy$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * Uint64 (*space_remaining)(void *) __attribute__((cdecl))
     * }
     */
    public static class space_remaining {

        space_remaining() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            long apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            SDL.C_LONG_LONG,
            SDL.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = SDL.upcallHandle(space_remaining.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(space_remaining.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static long invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (long) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout space_remaining$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("space_remaining"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint64 (*space_remaining)(void *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout space_remaining$layout() {
        return space_remaining$LAYOUT;
    }

    private static final long space_remaining$OFFSET = 88;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint64 (*space_remaining)(void *) __attribute__((cdecl))
     * }
     */
    public static final long space_remaining$offset() {
        return space_remaining$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint64 (*space_remaining)(void *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment space_remaining(MemorySegment struct) {
        return struct.get(space_remaining$LAYOUT, space_remaining$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint64 (*space_remaining)(void *) __attribute__((cdecl))
     * }
     */
    public static void space_remaining(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(space_remaining$LAYOUT, space_remaining$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

