// Generated by jextract

package org.sdl3;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPURenderStateDesc {
 *     Uint32 version;
 *     SDL_GPUShader *fragment_shader;
 *     Sint32 num_sampler_bindings;
 *     const SDL_GPUTextureSamplerBinding *sampler_bindings;
 *     Sint32 num_storage_textures;
 *     SDL_GPUTexture *const *storage_textures;
 *     Sint32 num_storage_buffers;
 *     SDL_GPUBuffer *const *storage_buffers;
 * }
 * }
 */
public class SDL_GPURenderStateDesc {

    SDL_GPURenderStateDesc() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL.C_INT.withName("version"),
        MemoryLayout.paddingLayout(4),
        SDL.C_POINTER.withName("fragment_shader"),
        SDL.C_INT.withName("num_sampler_bindings"),
        MemoryLayout.paddingLayout(4),
        SDL.C_POINTER.withName("sampler_bindings"),
        SDL.C_INT.withName("num_storage_textures"),
        MemoryLayout.paddingLayout(4),
        SDL.C_POINTER.withName("storage_textures"),
        SDL.C_INT.withName("num_storage_buffers"),
        MemoryLayout.paddingLayout(4),
        SDL.C_POINTER.withName("storage_buffers")
    ).withName("SDL_GPURenderStateDesc");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt version$LAYOUT = (OfInt)$LAYOUT.select(groupElement("version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static final OfInt version$layout() {
        return version$LAYOUT;
    }

    private static final long version$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static final long version$offset() {
        return version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static int version(MemorySegment struct) {
        return struct.get(version$LAYOUT, version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 version
     * }
     */
    public static void version(MemorySegment struct, int fieldValue) {
        struct.set(version$LAYOUT, version$OFFSET, fieldValue);
    }

    private static final AddressLayout fragment_shader$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("fragment_shader"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUShader *fragment_shader
     * }
     */
    public static final AddressLayout fragment_shader$layout() {
        return fragment_shader$LAYOUT;
    }

    private static final long fragment_shader$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUShader *fragment_shader
     * }
     */
    public static final long fragment_shader$offset() {
        return fragment_shader$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUShader *fragment_shader
     * }
     */
    public static MemorySegment fragment_shader(MemorySegment struct) {
        return struct.get(fragment_shader$LAYOUT, fragment_shader$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUShader *fragment_shader
     * }
     */
    public static void fragment_shader(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(fragment_shader$LAYOUT, fragment_shader$OFFSET, fieldValue);
    }

    private static final OfInt num_sampler_bindings$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_sampler_bindings"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Sint32 num_sampler_bindings
     * }
     */
    public static final OfInt num_sampler_bindings$layout() {
        return num_sampler_bindings$LAYOUT;
    }

    private static final long num_sampler_bindings$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Sint32 num_sampler_bindings
     * }
     */
    public static final long num_sampler_bindings$offset() {
        return num_sampler_bindings$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Sint32 num_sampler_bindings
     * }
     */
    public static int num_sampler_bindings(MemorySegment struct) {
        return struct.get(num_sampler_bindings$LAYOUT, num_sampler_bindings$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Sint32 num_sampler_bindings
     * }
     */
    public static void num_sampler_bindings(MemorySegment struct, int fieldValue) {
        struct.set(num_sampler_bindings$LAYOUT, num_sampler_bindings$OFFSET, fieldValue);
    }

    private static final AddressLayout sampler_bindings$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sampler_bindings"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const SDL_GPUTextureSamplerBinding *sampler_bindings
     * }
     */
    public static final AddressLayout sampler_bindings$layout() {
        return sampler_bindings$LAYOUT;
    }

    private static final long sampler_bindings$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const SDL_GPUTextureSamplerBinding *sampler_bindings
     * }
     */
    public static final long sampler_bindings$offset() {
        return sampler_bindings$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const SDL_GPUTextureSamplerBinding *sampler_bindings
     * }
     */
    public static MemorySegment sampler_bindings(MemorySegment struct) {
        return struct.get(sampler_bindings$LAYOUT, sampler_bindings$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const SDL_GPUTextureSamplerBinding *sampler_bindings
     * }
     */
    public static void sampler_bindings(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(sampler_bindings$LAYOUT, sampler_bindings$OFFSET, fieldValue);
    }

    private static final OfInt num_storage_textures$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_storage_textures"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Sint32 num_storage_textures
     * }
     */
    public static final OfInt num_storage_textures$layout() {
        return num_storage_textures$LAYOUT;
    }

    private static final long num_storage_textures$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Sint32 num_storage_textures
     * }
     */
    public static final long num_storage_textures$offset() {
        return num_storage_textures$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Sint32 num_storage_textures
     * }
     */
    public static int num_storage_textures(MemorySegment struct) {
        return struct.get(num_storage_textures$LAYOUT, num_storage_textures$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Sint32 num_storage_textures
     * }
     */
    public static void num_storage_textures(MemorySegment struct, int fieldValue) {
        struct.set(num_storage_textures$LAYOUT, num_storage_textures$OFFSET, fieldValue);
    }

    private static final AddressLayout storage_textures$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("storage_textures"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *const *storage_textures
     * }
     */
    public static final AddressLayout storage_textures$layout() {
        return storage_textures$LAYOUT;
    }

    private static final long storage_textures$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *const *storage_textures
     * }
     */
    public static final long storage_textures$offset() {
        return storage_textures$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *const *storage_textures
     * }
     */
    public static MemorySegment storage_textures(MemorySegment struct) {
        return struct.get(storage_textures$LAYOUT, storage_textures$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *const *storage_textures
     * }
     */
    public static void storage_textures(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(storage_textures$LAYOUT, storage_textures$OFFSET, fieldValue);
    }

    private static final OfInt num_storage_buffers$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_storage_buffers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Sint32 num_storage_buffers
     * }
     */
    public static final OfInt num_storage_buffers$layout() {
        return num_storage_buffers$LAYOUT;
    }

    private static final long num_storage_buffers$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Sint32 num_storage_buffers
     * }
     */
    public static final long num_storage_buffers$offset() {
        return num_storage_buffers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Sint32 num_storage_buffers
     * }
     */
    public static int num_storage_buffers(MemorySegment struct) {
        return struct.get(num_storage_buffers$LAYOUT, num_storage_buffers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Sint32 num_storage_buffers
     * }
     */
    public static void num_storage_buffers(MemorySegment struct, int fieldValue) {
        struct.set(num_storage_buffers$LAYOUT, num_storage_buffers$OFFSET, fieldValue);
    }

    private static final AddressLayout storage_buffers$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("storage_buffers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUBuffer *const *storage_buffers
     * }
     */
    public static final AddressLayout storage_buffers$layout() {
        return storage_buffers$LAYOUT;
    }

    private static final long storage_buffers$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUBuffer *const *storage_buffers
     * }
     */
    public static final long storage_buffers$offset() {
        return storage_buffers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUBuffer *const *storage_buffers
     * }
     */
    public static MemorySegment storage_buffers(MemorySegment struct) {
        return struct.get(storage_buffers$LAYOUT, storage_buffers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUBuffer *const *storage_buffers
     * }
     */
    public static void storage_buffers(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(storage_buffers$LAYOUT, storage_buffers$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

