// Generated by jextract

package org.sdl3;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*SDL_AudioPostmixCallback)(void *, const SDL_AudioSpec *, float *, int) __attribute__((cdecl))
 * }
 */
public class SDL_AudioPostmixCallback {

    SDL_AudioPostmixCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment userdata, MemorySegment spec, MemorySegment buffer, int buflen);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        SDL.C_POINTER,
        SDL.C_POINTER,
        SDL.C_POINTER,
        SDL.C_INT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = SDL.upcallHandle(SDL_AudioPostmixCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(SDL_AudioPostmixCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr,MemorySegment userdata, MemorySegment spec, MemorySegment buffer, int buflen) {
        try {
             DOWN$MH.invokeExact(funcPtr, userdata, spec, buffer, buflen);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

