// Generated by jextract

package org.sdl3;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef const void *(*SDL_ClipboardDataCallback)(void *, const char *, size_t *) __attribute__((cdecl))
 * }
 */
public class SDL_ClipboardDataCallback {

    SDL_ClipboardDataCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        MemorySegment apply(MemorySegment userdata, MemorySegment mime_type, MemorySegment size);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        SDL.C_POINTER,
        SDL.C_POINTER,
        SDL.C_POINTER,
        SDL.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = SDL.upcallHandle(SDL_ClipboardDataCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(SDL_ClipboardDataCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment userdata, MemorySegment mime_type, MemorySegment size) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, userdata, mime_type, size);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

